### PR TITLE
pin lodash version

### PR DESCRIPTION
**Pull request by aprilb**
Urgent PR per:
https://github.com/lodash/lodash/issues/861

### CODE REVIEW

**Comment by ifandelse** [comment]
@aprilb you have any issues with me pinning it to 2.4.1? (both package.json and bower.json are set to that & I'd like to keep them aligned)

**Comment by aprilb** [comment]
@ifandelse No problem at all.  Sounds good. :+1:

**Comment by ifandelse** [comment]
@aprilb OK - I checked out the PR locally, specified ~2.4.1 and pushed to master. Will component pick this up automatically, or do you need me to bump the version/patch up on machina? Thanks so much, btw, for reaching out and letting me know. I'd completely forgotten I'd set it wide open when I converted from underscore to lodash. *My bad!*

**Comment by aprilb** [comment]
@ifandelse looks like a version/patch is needed for machina. thanks!

**Comment by ifandelse** [comment]
@aprilb done, thanks! (Turns out, my head has been so wrapped up in the v0.5 machina changes that I'd only updated the package.json as of the last tag. component.json now shows v0.4.2. :smile:

**Comment by aprilb** [comment]
@ifandelse sweet!  thanks again!

**Pull request closed without merging**
